# Exploratory Data Analysis
Importing the raw data to understand the columns and data available to me and to determine the vision of my dashboard.

In [2]:
import pandas as pd

# Importing file
file_path = "Coffee Dashboard.xlsx"
df = pd.read_excel(file_path, sheet_name="Raw Data")

df

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [ ]:
print("\nShape:", df.shape) # (row, col)
print("\nColumns:", df.columns)

Shape: (3636, 7)

Columns: Index(['date', 'datetime', 'cash_type', 'card', 'money', 'coffee_name',
       'Time'],
      dtype='object')

In [ ]:
print("\nData Types")
print(df.dtypes)

# Looking for any null values in the columns I plan to use
print("\nMissing Values")
print(df.isnull().sum())

Data Types
date           datetime64[ns]
datetime       datetime64[ns]
cash_type              object
card                   object
money                 float64
coffee_name            object
Time                   object
dtype: object

Missing Values
date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
Time            0
dtype: int64

In [26]:
# Checking for duplicate rows
print(df.duplicated().sum())

0

In [3]:
# Replacing the original date time with the datetime_col
datetime_col = "datetime"

# Converting column to datetime
df[datetime_col] = pd.to_datetime(df[datetime_col])

# Creating a time only column in HH:MM:SS AM/PM format
df["Time"] = df[datetime_col].dt.strftime("%I:%M:%S %p")

# Finding the earliest and latest time
earliest_time = df[datetime_col].dt.time.min()
latest_time = df[datetime_col].dt.time.max()

print("Earliest time:", earliest_time)
print("Latest time:", latest_time)

Earliest time: 06:50:04.455000
Latest time: 22:59:18.544000

In [ ]:
# Comparing Time and datetime
print(df[[datetime_col, "Time"]].head())

                 datetime         Time
0 2024-03-01 10:15:50.520  10:15:50 AM
1 2024-03-01 12:19:22.539  12:19:22 PM
2 2024-03-01 12:20:18.089  12:20:18 PM
3 2024-03-01 13:46:33.006  01:46:33 PM
4 2024-03-01 13:48:14.626  01:48:14 PM

In [ ]:
# Stat summary
df.describe()

,date,datetime,money
count,3636,3636,3636.000000
mean,2024-09-30 11:56:02.376237568,2024-10-01 02:35:30.535053568,31.746859
min,2024-03-01 00:00:00,2024-03-01 10:15:50.520000,18.120000
25%,2024-07-03 00:00:00,2024-07-03 16:54:06.084750080,27.920000
50%,2024-10-06 12:00:00,2024-10-07 02:55:12.649500160,32.820000
75%,2025-01-08 00:00:00,2025-01-08 07:55:20.299750144,35.760000
max,2025-03-23 00:00:00,2025-03-23 18:11:38.635000,40.000000
std,NaN,NaN,4.919926

In [ ]:
# Checking top coffee purchases
print(df["coffee_name"].value_counts())

coffee_name
Americano with Milk    824
Latte                  782
Americano              578
Cappuccino             501
Cortado                292
Hot Chocolate          282
Cocoa                  243
Espresso               134
Name: count, dtype: int64

In [ ]:
# Final Check
df.head()

,date,datetime,cash_type,card,money,coffee_name,Time
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,10:15:50 AM
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,12:19:22 PM
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,12:20:18 PM
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,01:46:33 PM
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,01:48:14 PM